Figshare data
NBISweden/workshop-reproducible-research pull request #211
Opened 2023-03-14 21:17 UTC by johnne

In this PR we remove the dependency on the `sra-tools` package for downloading fastq files. This is because the package is having network errors in some cases when using `fastq-dump`, see for instance:

- https://github.com/ncbi/sra-tools/issues/790
- https://github.com/ncbi/sra-tools/issues/777
- https://github.com/ncbi/sra-tools/issues/788

2023-03-17 09:16 UTC, fasterius commented on pages/conda/conda-2-the-basics.md
Instances of `conda` needs to be changed to `mamba` where applicable, to be in line with #209.

2023-03-17 09:20 UTC, fasterius requested changes
Great work! Some instances of `conda` needs to be changed to `mamba` to adhere to the new changes introduced in #209. The Nextflow material will also need to be updated accordingly.

2023-03-18 06:26 UTC, johnne commented
@fasterius, thanks! Yes I wanted to wait with changing conda in this branch before that PR was merged. Will start updating. Do you want to handle the nextflow changes? I was thinking maybe you wanted to do that change together with the rest of the Nextflow update, or I could change it first?

2023-03-20 08:33 UTC, fasterius commented
Sure, I can do the Nextflow things! I will try to do it this week or next.

2023-03-21 11:42 UTC, merged